[[pages]]
path = "/"
screenshotTimestamp = "2026-03-22T01:05:35Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/77c0f663-3078-4590-9cd1-4abcc76be09d/6baa078b-24df-45ff-8338-b8657ce66113/slJJt0r"

[[pages]]
path = "/our-services"
screenshotTimestamp = "2026-03-21T20:34:58Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/77c0f663-3078-4590-9cd1-4abcc76be09d/e6841b9b-4e6c-4643-9139-08d2dbac146c/D4yXABt"

[[pages]]
path = "/contact"
screenshotTimestamp = "2026-03-21T20:34:44Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/77c0f663-3078-4590-9cd1-4abcc76be09d/e6841b9b-4e6c-4643-9139-08d2dbac146c/j1Mv0Cn"

[[pages]]
path = "/seasonal-plans"
screenshotTimestamp = "2026-03-21T20:34:41Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/77c0f663-3078-4590-9cd1-4abcc76be09d/e6841b9b-4e6c-4643-9139-08d2dbac146c/xmbtCsu"

[[pages]]
path = "/blog"
screenshotTimestamp = "2026-03-21T20:34:39Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/77c0f663-3078-4590-9cd1-4abcc76be09d/e6841b9b-4e6c-4643-9139-08d2dbac146c/yrB6R6O"

[[pages]]
path = "/blog/deck-wash-level-1"
screenshotTimestamp = "2026-03-20T15:50:58Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/77c0f663-3078-4590-9cd1-4abcc76be09d/e6841b9b-4e6c-4643-9139-08d2dbac146c/asgdDWh"

[[pages]]
path = "/deck-polishing"
screenshotTimestamp = "2026-03-21T20:22:57Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/77c0f663-3078-4590-9cd1-4abcc76be09d/e6841b9b-4e6c-4643-9139-08d2dbac146c/gkJTHi9"

[[pages]]
path = "/bottom-prep"
screenshotTimestamp = "2026-03-20T17:27:07Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/77c0f663-3078-4590-9cd1-4abcc76be09d/e6841b9b-4e6c-4643-9139-08d2dbac146c/OzjfvSj"

[[pages]]
path = "/protections"
screenshotTimestamp = "2026-03-20T17:27:10Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/77c0f663-3078-4590-9cd1-4abcc76be09d/e6841b9b-4e6c-4643-9139-08d2dbac146c/VDSzhp3"

[[pages]]
path = "/extra-services"
screenshotTimestamp = "2026-03-20T17:43:51Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/77c0f663-3078-4590-9cd1-4abcc76be09d/e6841b9b-4e6c-4643-9139-08d2dbac146c/IkYhaeN"

[[pages]]
path = "/our-work"
screenshotTimestamp = "2026-03-21T20:35:26Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/77c0f663-3078-4590-9cd1-4abcc76be09d/e6841b9b-4e6c-4643-9139-08d2dbac146c/whEFusS"

[[pages]]
path = "/meet-the-team"
screenshotTimestamp = "2026-03-22T01:10:06Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/77c0f663-3078-4590-9cd1-4abcc76be09d/6baa078b-24df-45ff-8338-b8657ce66113/xIyQGiD"

[[pages]]
path = "/deck-washes"
screenshotTimestamp = "2026-03-21T16:02:39Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/77c0f663-3078-4590-9cd1-4abcc76be09d/e6841b9b-4e6c-4643-9139-08d2dbac146c/br7iymF"

[[pages]]
path = "/team"
screenshotTimestamp = "2026-03-21T20:22:26Z"
screenshotUri = "https://storage.googleapis.com/screenshot-production-us-central1/77c0f663-3078-4590-9cd1-4abcc76be09d/e6841b9b-4e6c-4643-9139-08d2dbac146c/EVWQisy"
